[tox]
minversion = 1.8
basepython = python3.8
envlist = py{38}-ansible-{2.12}
skipsdist = true

[testenv]
passenv = *
deps =
    -r tox-requirements.txt
    2.13: ansible == 2.13.*
commands =
    {posargs:molecule test -s tox --destroy always}
