---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centoc_ansib:latest
    pre_build_image: true
    privileged: true
    command: /sbin/init
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroupns_mode: host 
provisioner:
  name: ansible
verifier:
  name: ansible
