---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: zzugly/centoc7_ansib:1.0.0
    pre_build_image: true
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host 
provisioner:
  name: ansible
verifier:
  name: ansible
